language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm run setup
  - npm run lint
  - npm test

after_success:
  - npm run coveralls

notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
